

package org.jub.kotlin.compiler.runners;

import com.intellij.testFramework.TestDataPath;
import org.jetbrains.kotlin.test.util.KtTestUtil;
import org.jetbrains.kotlin.test.TargetBackend;
import org.jetbrains.kotlin.test.TestMetadata;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;

import java.io.File;
import java.util.regex.Pattern;

/** This class is generated by {@link org.jub.kotlin.compiler.GenerateTestsKt}. DO NOT MODIFY MANUALLY */
@SuppressWarnings("all")
@TestMetadata("shallowsize-plugin/src/test/resources/org/jub/kotlin/compiler/code-gen/fir/box")
@TestDataPath("$PROJECT_ROOT")
public class FirBoxTestGenerated extends AbstractFirBoxTest {
    @Test
    public void testAllFilesPresentInBox() throws Exception {
        KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("shallowsize-plugin/src/test/resources/org/jub/kotlin/compiler/code-gen/fir/box"), Pattern.compile("^(.+)\\.kt$"), null, TargetBackend.JVM_IR, true);
    }

    @Nested
    @TestMetadata("shallowsize-plugin/src/test/resources/org/jub/kotlin/compiler/code-gen/fir/box/shallowSizeExists")
    @TestDataPath("$PROJECT_ROOT")
    public class ShallowSizeExists {
        @Test
        public void testAllFilesPresentInShallowSizeExists() throws Exception {
            KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("shallowsize-plugin/src/test/resources/org/jub/kotlin/compiler/code-gen/fir/box/shallowSizeExists"), Pattern.compile("^(.+)\\.kt$"), null, TargetBackend.JVM_IR, true);
        }

        @Test
        @TestMetadata("shallowSizeExists.kt")
        public void testShallowSizeExists() throws Exception {
            runTest("shallowsize-plugin/src/test/resources/org/jub/kotlin/compiler/code-gen/fir/box/shallowSizeExists/shallowSizeExists.kt");
        }
    }

    @Nested
    @TestMetadata("shallowsize-plugin/src/test/resources/org/jub/kotlin/compiler/code-gen/fir/box/silly")
    @TestDataPath("$PROJECT_ROOT")
    public class Silly {
        @Test
        public void testAllFilesPresentInSilly() throws Exception {
            KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("shallowsize-plugin/src/test/resources/org/jub/kotlin/compiler/code-gen/fir/box/silly"), Pattern.compile("^(.+)\\.kt$"), null, TargetBackend.JVM_IR, true);
        }

        @Test
        @TestMetadata("MoreSilly.kt")
        public void testMoreSilly() throws Exception {
            runTest("shallowsize-plugin/src/test/resources/org/jub/kotlin/compiler/code-gen/fir/box/silly/MoreSilly.kt");
        }
    }
}
